echo "You can add custom installation logic here"
echo "Provided environment variables:"
echo "  PKG_NAME=$PKG_NAME"
echo "  PKG_VERSION=$PKG_VERSION"
echo "  PKG_MAINTAINER=$PKG_MAINTAINER"
echo "  PKG_DESCRIPTION=$PKG_DESCRIPTION"
echo "  PKG_TAGS=$PKG_TAGS"
echo "  PKG_INSTALL_DIR=$PKG_INSTALL_DIR"
echo "  PKG_SOURCE_DIR=$PKG_SOURCE_DIR"
echo "Test file" > "$PKG_INSTALL_DIR/$PKG_NAME-installed.txt"
echo "  PKG_NAME=$PKG_NAME" >> "$PKG_INSTALL_DIR/$PKG_NAME-installed.txt"
echo "  PKG_VERSION=$PKG_VERSION" >> "$PKG_INSTALL_DIR/$PKG_NAME-installed.txt"
echo "  PKG_MAINTAINER=$PKG_MAINTAINER" >> "$PKG_INSTALL_DIR/$PKG_NAME-installed.txt"
echo "  PKG_DESCRIPTION=$PKG_DESCRIPTION" >> "$PKG_INSTALL_DIR/$PKG_NAME-installed.txt"
echo "  PKG_TAGS=$PKG_TAGS" >> "$PKG_INSTALL_DIR/$PKG_NAME-installed.txt"
echo "  PKG_INSTALL_DIR=$PKG_INSTALL_DIR" >> "$PKG_INSTALL_DIR/$PKG_NAME-installed.txt"
echo "  PKG_SOURCE_DIR=$PKG_SOURCE_DIR" >> "$PKG_INSTALL_DIR/$PKG_NAME-installed.txt"
sleep 10